bookshop/urls.py
from django.urls import path

from .views import (
    BookListView,
    CategoryDetailView,
    SubCategoryDetailView,
    BookDetailView,
    OrderingCreateView,
    AuthorDetailView,
    like_review,
    RegistrationUser,
    LoginUser,
    personal_account,
    CustomerOrderDetail,
    logout_view,
    PublisherDetailView,
    BookSeriesDetailView,
    form_review,
)

urlpatterns = [
    path('', BookListView.as_view(), name='home_page'),
    path('category-detail/<int:pk>/', CategoryDetailView.as_view(), name='category_detail'),
    path('subcategory-detail/<int:pk>/', SubCategoryDetailView.as_view(), name='subcategory_detail'),
    path('book-detail/<int:pk>/', BookDetailView.as_view(), name='book_detail'),
    path('book-detail-like/<int:pk>/', like_review, name='like_review'),
    path('author-detail/<int:pk>/', AuthorDetailView.as_view(), name='author_detail'),
    path('publisher-detail/<int:pk>/', PublisherDetailView.as_view(), name='publisher_detail'),
    path('bookseries-detail/<int:pk>/', BookSeriesDetailView.as_view(), name='bookseries_detail'),
    path('ordering/', OrderingCreateView.as_view(), name='ordering_view'),
    path('registration/', RegistrationUser.as_view(), name='registration_view'),
    path('login/', LoginUser.as_view(), name='login_view'),
    path('logout/', logout_view, name='logout'),
    path('personal-account/', personal_account, name='personal_account'),
    path('order-detail/<int:pk>/', CustomerOrderDetail.as_view(), name='order_detail'),
    path('form-review/<int:pk>/', form_review, name='review_form'),
]

cart/urls.py
from django.urls import path

from .views import (
    cart_add,
    open_cart,
    clear_cart,
    remove_from_cart,
)

app_name = 'cart'

urlpatterns = [
    path('<int:pk>/', cart_add, name='cart_add'),
    path('open-cart/', open_cart, name='open_cart'),
    path('clear-cart/', clear_cart, name='clear_cart'),
    path('remove-from-cart/<int:pk>/', remove_from_cart, name='remove_from_cart'),
]

e_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from e_shop import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('booklover/', include('bookshop.urls')),
    path('cart/', include('cart.urls')),
    path('payment/', include('liqpay_api.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

liqpay_api/urls.py
from django.urls import path

from .views import PayView, PayCallbackView

app_name = 'payment'

urlpatterns = [
    path('pay/', PayView.as_view(), name='pay_view'),
    path('pay-callback/', PayCallbackView.as_view(), name='pay_callback'),
]

bookshop/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.urls import reverse



class Category(models.Model):
    title = models.CharField('Назва категорії', max_length=50)
    subcategory = models.ManyToManyField('Subcategory', blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('category_detail', args=(self.pk,))


class Subcategory(models.Model):
    title = models.CharField('*Назва підкатегорії', max_length=50)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('subcategory_detail', args=(self.pk,))


class Book(models.Model):
    LANGUAGE = (
        ('українська', 'Українська'),
        ('російська', 'Російська'),
        ('англійська', 'Англійська')
    )

    ILLUSTRATIONS = (
        ('чорно-білі', 'Чорно-білі'),
        ('багатокольорові', 'Багатокольорові'),
        ('без зображень', 'Без зображень')
    )

    PALETTE = (
        ('тверда', 'Тверда'),
        ("м'яка", "М'яка")
    )

    PAPER = (
        ('офсетний', 'Офсетний'),
        ('мелований', 'Мелований'),
    )

    BOOK_TYPE = (
        ('паперова', 'Паперова'),
        ('електронна', 'Електронна')
    )

    author = models.ManyToManyField(
        'Author',
        verbose_name='Автор',
        blank=True,
        default='Не обрано'
    )

    interpreter = models.ManyToManyField(
        'Interpreter',
        verbose_name='Перекладач',
        blank=True,
        default='Не обрано',
    )

    illustrator = models.ManyToManyField(
        'Illustrator',
        verbose_name='Ілюстратор',
        blank=True,
        default='Не обрано',
    )

    publisher = models.ForeignKey(
        'Publisher',
        verbose_name='*Видавництво',
        on_delete=models.SET_DEFAULT,
        default='Не обрано'
    )

    book_series = models.ForeignKey(
        'BookSeries',
        verbose_name='Серія книг',
        on_delete=models.SET_DEFAULT,
        default='Не обрано',
        blank=True
    )

    category = models.ForeignKey(
        'Subcategory',
        verbose_name='Категорія',
        on_delete=models.SET_DEFAULT,
        default='Не обрано',
        blank=True
    )

    edition = models.IntegerField(verbose_name='Тираж', blank=True, null=True)
    weight = models.IntegerField(verbose_name='Вага', blank=True, null=True)
    first_publication_year = models.IntegerField(verbose_name='Рік першого видання', blank=True, null=True)
    rating = models.IntegerField(verbose_name='Рейтинг', default=0, blank=True, null=True)

    price = models.IntegerField(verbose_name='*Ціна')
    publication_year = models.IntegerField(verbose_name='*Рік видання')
    page_count = models.IntegerField(verbose_name='*Кількість сторінок')

    language = models.CharField(choices=LANGUAGE, max_length=15, verbose_name='*Мова')
    palette = models.CharField(choices=PALETTE, max_length=30, verbose_name='*Палітурка')
    paper = models.CharField(choices=PAPER, max_length=30, verbose_name='*Папір')
    book_type = models.CharField(choices=BOOK_TYPE, max_length=30, verbose_name='*Тип')

    Illustrations = models.CharField(choices=ILLUSTRATIONS, max_length=25, verbose_name='Ілюстрації', blank=True,
                                     null=True)

    title = models.CharField('*Назва книги', null=True, max_length=100)
    format = models.CharField('*Формат книги (приклад: 145х215 мм)', max_length=100)
    isbn = models.CharField('*isbn', max_length=25)
    code_product = models.CharField('*Код товару', max_length=9)

    cover_photo = models.ImageField('*Фото', upload_to='img')

    description = models.TextField(null=True, verbose_name='Усе про книжку')

    def __str__(self):
        return f'{self.title}: ({self.code_product})'

    def get_absolute_url(self):
        return reverse('book_detail', args=(self.pk,))

    def average_rating(self):
        review_list = [int(i.rating) for i in Review.objects.filter(book=self)]
        rating = sum(review_list) / len(review_list)
        return int(rating)

    def absolute_average_rating(self):
        review_list = [int(i.rating) for i in Review.objects.filter(book=self)]
        rating = sum(review_list) / len(review_list)
        return round(rating, 1)

    def get_rating_by_grade(self):
        review_list = [int(i.rating) for i in Review.objects.filter(book=self)]
        length = len(review_list)
        star_1, star_2, star_3, star_4, star_5 = [True for star in review_list if star in (1,)], \
                                                 [True for star in review_list if star in (2,)], \
                                                 [True for star in review_list if star in (3,)], \
                                                 [True for star in review_list if star in (4,)], \
                                                 [True for star in review_list if star in (5,)]
        star_1, star_2, star_3, star_4, star_5 = sum(star_1) * 100 // length, \
                                                 sum(star_2) * 100 // length, \
                                                 sum(star_3) * 100 // length, \
                                                 sum(star_4) * 100 // length, \
                                                 sum(star_5) * 100 // length

        return star_1, star_2, star_3, star_4, star_5

    def count_review(self):
        review_list = ['.' for i in Review.objects.filter(book=self)]
        return len(review_list)


class Author(models.Model):
    name = models.CharField("*Ім'я автора", max_length=100)

    birthdate = models.DateField('Дата народження', blank=True, null=True)
    death_date = models.DateField('Дата смерті', blank=True, null=True)
    biography = models.TextField('Біографія', blank=True, null=True)
    photo = models.ImageField('Фото', upload_to='img', blank=True, null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('author_detail', args=(self.pk,))


class Publisher(models.Model):
    title = models.CharField('*Назва видавництва', max_length=100)
    photo = models.ImageField('*Фото', upload_to='img')
    info = models.TextField('*Опис видавництва')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('publisher_detail', args=(self.pk,))


class BookSeries(models.Model):
    title = models.CharField('*Серія книг', max_length=100)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('bookseries_detail', args=(self.pk,))


class Interpreter(models.Model):
    title = models.CharField('*Перекладач', max_length=100)

    def __str__(self):
        return self.title


class Illustrator(models.Model):
    title = models.CharField('*Ілюстратор', max_length=100)

    def __str__(self):
        return self.title


class CustomerOrder(models.Model):
    order_items = models.TextField()
    mail = models.CharField(max_length=100, verbose_name='Електронна пошта')
    city = models.CharField(max_length=100, verbose_name='Місто доставки')
    post_department = models.CharField(max_length=150, verbose_name='Поштове відділення(номер, адреса)')
    phone_number = models.CharField(max_length=15, null=True, verbose_name='Номер телефона')
    status_success = models.BooleanField(null=True)
    total_price = models.IntegerField()
    date = models.DateField(auto_now_add=True, null=True)

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        blank=True,
        null=True
    )

    def __str__(self):
        return f'{self.date}'

    def get_absolute_url(self):
        return reverse('order_detail', args=(self.pk,))


class Review(models.Model):
    RATING = (
        ('1', 'Жахливо'),
        ('2', 'Погано'),
        ('3', 'Середньо'),
        ('4', 'Добре'),
        ('5', 'Чудово')
    )

    title = models.CharField('Заголовок', max_length=100)
    body = models.TextField('Рецензія', max_length=2500)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    rating = models.CharField('Рейтинг', choices=RATING, max_length=100)


    def __str__(self):
        return f'{self.user}: {self.title}'

    def count_like(self):
        like_list = LikeReview.objects.filter(review=self)
        return len(like_list)

    def count_dislike(self):
        like_list = DislikeReview.objects.filter(review=self)
        return len(like_list)


class LikeDislikeManager(models.Manager):

    def get_or_none(self, **kwargs):
        try:
            return self.get(**kwargs)
        except ObjectDoesNotExist:
            return None


class LikeReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)

    objects = LikeDislikeManager()


class DislikeReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)

    objects = LikeDislikeManager()

liqpay_api/models.py
from django.db import models

# Create your models here.

bookshop/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.models import User

from bookshop.models import CustomerOrder, Review


class CustomerOrderForm(forms.ModelForm):
    class Meta:
        model = CustomerOrder
        fields = ['mail', 'city', 'post_department', 'phone_number']


class RegistrationUserForm(forms.ModelForm):
    username = forms.CharField(required=True, max_length=25, label='Логін')
    password = forms.CharField(max_length=30, required=True, widget=forms.PasswordInput(), label='пароль')
    password_confirm = forms.CharField(max_length=30, required=True, widget=forms.PasswordInput(), label='пароль')
    email = forms.EmailField(required=True, label='електронна пошта')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('зареєструватися', 'Зареєструватися'))

    class Meta:
        model = User
        fields = ('username', 'email', 'password', 'password_confirm')

    def clean_password_confirm(self):
        password_one = self.cleaned_data.get('password')
        password_two = self.cleaned_data.get('password_confirm')
        password_has_num = [True for sym in password_one if sym.isdigit()]

        if password_one != password_two:
            raise forms.ValidationError('Паролі не співпадають')
        if len(password_one) < 8:
            raise forms.ValidationError('Пароль має бути довше 8 символів')
        if not password_one[0].isalpha():
            raise forms.ValidationError('Перший символ у паролі має бути великою літерою')
        if not password_one[0].isupper():
            raise forms.ValidationError('Перший символ у паролі має бути великою літерою')
        if not sum(password_has_num) > 0:
            raise forms.ValidationError('Пароль повинен містити хоча б одне число')

        return password_two

    def clean_email(self):
        email = self.cleaned_data.get('email')
        check_mail = User.objects.filter(email=email)

        if len(check_mail) > 0:
            raise forms.ValidationError('Ця електронна адреса вже використовується')

        return email


class LoginUserForm(forms.Form):
    username = forms.CharField(required=True, max_length=25, label='Логін')
    password = forms.CharField(max_length=30, required=True, widget=forms.PasswordInput(), label='Пароль')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('увійти', 'Увійти'))

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        check_username = User.objects.filter(username=username)

        if not len(check_username):
            raise forms.ValidationError('Користувача с таким логіном не знайдено')

        check_password = authenticate(username=username, password=password)

        if check_password is None:
            raise forms.ValidationError('Неправильний пароль')

        return self.cleaned_data


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['title', 'body', 'rating']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('залишити рецензiю', 'Залишити рецензiю'))

cart/views.py
from django.shortcuts import render, redirect

from bookshop.models import Book, Category
from bookshop.utilities import user_is_active
from .cart import Cart


def cart_add(request, **kwargs):
    cart = Cart(request)
    cart.add(kwargs['pk'])

    return redirect('cart:open_cart')


def open_cart(request):
    cart = Cart(request)

    if request.method == 'GET':
        if 'add' in request.GET:
            cart.update_quantity(request.GET.get('add'), 1)
            return redirect('cart:open_cart')
        elif 'remove' in request.GET:
            cart.update_quantity(request.GET.get('remove'), -1)
            return redirect('cart:open_cart')

    books_ids = cart.cart.keys()
    object_list = Book.objects.filter(pk__in=books_ids)

    display_cart = {}

    for i in range(len(books_ids)):
        current_book = object_list[i]
        display_cart[str(current_book.pk)] = {
            'current_book': current_book,
            'quantity': cart.cart[str(current_book.pk)]['quantity'],
            'total_price': cart.cart[str(current_book.pk)]['quantity'] * cart.cart[str(current_book.pk)]['price']
        }

        if display_cart[str(current_book.pk)]['quantity'] <= 1:
            display_cart[str(current_book.pk)]['is_one'] = True
        else:
            display_cart[str(current_book.pk)]['is_one'] = False

    total_price = 0
    for value in display_cart.values():
        total_price += value['total_price']

    context = {
        'display_cart': display_cart,
        'books_ids': books_ids,
        'total_price': total_price,
        'category_list': Category.objects.all(),
    }
    context = context | user_is_active(request)
    return render(request, 'bookshop/cart.html', context)


def clear_cart(request):
    cart = Cart(request)
    cart.clear()

    return redirect('cart:open_cart')


def remove_from_cart(request, pk):
    cart = Cart(request)
    cart.remove(pk)

    return redirect('cart:open_cart')

bookshop/templates/bookshop/bookseries_detail.html
{% extends 'bookshop/base/base.html' %}

{% block  content %}
    <div class="container mb-5">
        <div class="row">
            <h1>
                Серія книг {{ object.title }}
            </h1>
        </div>
    </div>

    {% include 'bookshop/includes/card_grid.html' %}
    {% include 'bookshop/includes/pagination.html' %}
{% endblock %}

bookshop/templates/bookshop/cart.html
{% extends 'bookshop/base/base.html' %}

{% block content %}
    <div class="container">
        <strong> Кошик </strong>
        {% for k, v in display_cart.items %}
            <div class="row gy-3">
                <div style="border-top: 1px black solid; min-weight: 100%" class="end"></div>

                <div class="col-xs-1 col-sm-3 col-md-2">
                    <img style="max-width: 100px" src="{{ v.current_book.cover_photo.url }}" alt="">
                </div>
                <div class="col-xs-1 col-sm-4 col-md-3">
                    <a style="text-decoration: none"
                       href="{{ v.current_book.get_absolute_url }}"> {{ v.current_book.title }}
                    </a>
                    <p> {{ v.current_book.price }} грн</p>
                </div>

                <div class="col-xs-1 col-sm col-md-5">
                    <form method="get">
                        <button name="add" value="{{ k }}" class="btn">
                            <svg xmlns="http://www.w3.org/2000/svg" width="49" height="49" fill="currentColor"
                                 class="bi bi-plus-square" viewBox="0 0 16 16">
                                <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                                <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
                            </svg>
                        </button>

                        <counter class="btn btn-primary"><strong> {{ v.quantity }} </strong></counter>

                        {% if v.is_one %}
                            <svg style="color: gray; margin-left: 19px" xmlns="http://www.w3.org/2000/svg" width="49"
                                 height="49" fill="currentColor"
                                 class="bi bi-dash-square" viewBox="0 0 16 16">
                                <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                                <path d="M4 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 4 8z"/>
                            </svg>
                        {% else %}
                            <button name="remove" value="{{ k }}" class="btn">
                                <svg xmlns="http://www.w3.org/2000/svg" width="49" height="49" fill="currentColor"
                                     class="bi bi-dash-square" viewBox="0 0 16 16">
                                    <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                                    <path d="M4 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 4 8z"/>
                                </svg>
                            </button>
                        {% endif %}
                    </form>
                Загальна ціна: {{ v.total_price }} грн
                </div>


                <div class="col-xs-1 col-sm col-md">
                    <svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" fill="currentColor"
                         class="bi bi-trash" viewBox="0 0 16 16">
                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                        <path fill-rule="evenodd"
                              d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                    </svg>
                    <a href="{% url 'cart:remove_from_cart' k %}">Видалити</a>
                </div>

                <div style="border-bottom: 1px black solid; min-weight: 100%" class="end"></div>
            </div>
        {% endfor %}
    </div>

    <div class="container">
        <div class="row">
            <div class="col-md-3 col-sm-4">
                {% if display_cart %}
                    <h5>Підсумок:
                        <color style="color: darkorange">{{ total_price }} грн</color>
                    </h5>
                {% endif %}
            </div>

            {% if display_cart %}
                <nav class="navbar bg-light">
                    <form class="container-fluid justify-content-start">
                        <button class="btn btn-warning me-2 my-2" type="button">
                            <a style="text-decoration: none; color: black" href="{% url 'ordering_view' %}">
                                <strong>
                                    Оформити замовлення
                                </strong></a>
                        </button>
                        <button class="btn btn-sm btn-danger" type="button">
                            <a style="text-decoration: none; color: black" href="{% url 'cart:clear_cart' %}">
                                <strong>
                                    Очистити корзину
                                </strong>
                            </a>
                        </button>
                    </form>
                </nav>
            {% endif %}
        </div>
    </div>
{% endblock %}

bookshop/templates/bookshop/category_detail.html
{% extends 'bookshop/base/base.html' %}

{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col">
                {% for subcategory in subcategory_list %}
                    <a style="text-decoration: none" href="{{ subcategory.get_absolute_url }}">
                        <p>
                            {{ subcategory }}
                        </p>
                    </a>
                {% endfor %}

            </div>
        </div>
    </div>
{% endblock %}

bookshop/templates/bookshop/index.html
{% extends 'bookshop/base/base.html' %}


{% block content %}
    {% include 'bookshop/includes/card_grid.html' %}
{% endblock %}

bookshop/templates/bookshop/liqpay_api.html
<div id="liqpay_checkout"></div>
<script>
    window.LiqPayCheckoutCallback = function() {
        LiqPayCheckout.init({
            data: "{{ data }}",
            signature: "{{ signature }}",
            embedTo: "#liqpay_checkout",
            mode: "embed" // embed || popup,
        }).on("liqpay.callback", function(data){
            console.log(data.status);
            console.log(data);
        }).on("liqpay.ready", function(data){
            // ready
        }).on("liqpay.close", function(data){
            // close
        });
    };
</script>
<script src="//static.liqpay.ua/libjs/checkout.js" async></script>

bookshop/templates/bookshop/login_page.html
{% extends 'bookshop/base/base.html' %}
{% load crispy_forms_tags %}

{% block  content %}
    {% if user_is_active %}
        <div class="container">
            <div class="row">
                <div class="col">
                    <h1>Ви вже увійшли</h1>
                </div>
            </div>
        </div>
    {% else %}
        <div class="container col-sm col-md-6 my-3">
            <h1>Вхід</h1>
            <form method="post">
                {% csrf_token %}
                {% crispy form %}
            </form>
            <br>
            <a style="text-decoration: none" href="{% url 'registration_view' %}">Немає облікового запису?</a>
        </div>
    {% endif %}
{% endblock %}

bookshop/templates/bookshop/order_detail.html
{% extends 'bookshop/base/base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                <h1>Інформація:</h1>
                <p>
                    {{ object.order_items }}
                </p>
                <h5>
                    Дата замовлення: {{ object.date }}
                </h5>
            </div>
        </div>
    </div>
{% endblock %}

bookshop/templates/bookshop/ordering.html
{% extends 'bookshop/base/base.html' %}
{% load dict_key %}

{% block content %}
    <div class="container">
        <div class="row mt-4">
            <form method="POST">
                {% csrf_token %}
                {% for field in form %}
                    <div class="mb-3">
                        <label for="inputOrderingData" class="form-label">{{ field.label }}</label>
                        {% if data %}
                            <input type="text" name={{ field.name }} class="form-control" id="inputOrderingData"
                                   aria-describedby="emailHelp"
                                   value={{ data|get_item:field.name }}>
                        {% else %}
                            <input type="text" name={{ field.name }} class="form-control" id="inputOrderingData"
                                   aria-describedby="emailHelp"
                            >
                        {% endif %}
                    </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">Оплата</button>
            </form>
        </div>
    </div>


{% endblock %}

bookshop/templates/bookshop/personal_account.html
{% extends 'bookshop/base/base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                <h1>Мої замовлення:</h1>
                {% for order in order_list %}
                    <p>
                        <a style="text-decoration: none" href="{{ order.get_absolute_url }}">
                            {{ order }}
                        </a>
                    </p>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

bookshop/templates/bookshop/publisher_detail.html
{% extends 'bookshop/base/base.html' %}

{% block  content %}
    <div class="container mb-5">
        <div class="row">
            <h1>
                Видавництво книг {{ object.title }}
            </h1>
            <div class="col-sm col-md-3">
                <img src="{{ object.photo.url }}" alt="">
            </div>
            <div class="col">
                {{ object.info|truncatechars:500 }}
                <p>
                    <button class="btn btn-primary" type="button" data-bs-toggle="collapse"
                            data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                        Читати повністю
                    </button>
                <div class="collapse" id="collapseExample">
                    <div class="card card-body">
                        {{ object.info|slice:"500:" }}
                    </div>
                </div>
                </p>
            </div>
        </div>
    </div>

    {% include 'bookshop/includes/card_grid.html' %}
    {% include 'bookshop/includes/pagination.html' %}
{% endblock %}

bookshop/templates/bookshop/register_page.html
{% extends 'bookshop/base/base.html' %}
{% load crispy_forms_tags %}

{% block  content %}
    <div class="container col-6 my-3">
        <form method="post">
            {% csrf_token %}
            {% crispy form %}
        </form>
        <div id="passwordHelpBlock" class="form-text">
            Ваша електронна адреса та ім’я користувача мають бути унікальними,
            пароль має складатися з 8-20 символів, містити літери та цифри та не містити пробілів,
            спеціальні символи або емодзі.
        </div>
    </div>
{% endblock %}

bookshop/templates/bookshop/review_form.html
{% extends 'bookshop/base/base.html' %}
{% load crispy_forms_tags %}


{% block  content %}
    <div class="container col-6 my-3">
        <form method="post">
            {% csrf_token %}
            {% crispy form %}
        </form>
    </div>
{% endblock %}

bookshop/templates/bookshop/subcategory_detail.html
{% extends 'bookshop/base/base.html' %}

{% block content %}
    {% include 'bookshop/includes/card_grid.html' %}
{% endblock %}