bookshop/urls.py
from django.urls import path

from .views import (
    BookListView,
    CategoryDetailView,
    SubCategoryDetailView,
    BookDetailView,
    OrderingCreateView,
    AuthorDetailView,
    like_review,
    RegistrationUser,
    LoginUser,
    personal_account,
    CustomerOrderDetail,
    logout_view,
    PublisherDetailView,
    BookSeriesDetailView,
    form_review,
)

urlpatterns = [
    path('', BookListView.as_view(), name='home_page'),
    path('category-detail/<int:pk>/', CategoryDetailView.as_view(), name='category_detail'),
    path('subcategory-detail/<int:pk>/', SubCategoryDetailView.as_view(), name='subcategory_detail'),
    path('book-detail/<int:pk>/', BookDetailView.as_view(), name='book_detail'),
    path('book-detail-like/<int:pk>/', like_review, name='like_review'),
    path('author-detail/<int:pk>/', AuthorDetailView.as_view(), name='author_detail'),
    path('publisher-detail/<int:pk>/', PublisherDetailView.as_view(), name='publisher_detail'),
    path('bookseries-detail/<int:pk>/', BookSeriesDetailView.as_view(), name='bookseries_detail'),
    path('ordering/', OrderingCreateView.as_view(), name='ordering_view'),
    path('registration/', RegistrationUser.as_view(), name='registration_view'),
    path('login/', LoginUser.as_view(), name='login_view'),
    path('logout/', logout_view, name='logout'),
    path('personal-account/', personal_account, name='personal_account'),
    path('order-detail/<int:pk>/', CustomerOrderDetail.as_view(), name='order_detail'),
    path('form-review/<int:pk>/', form_review, name='review_form'),
]

cart/urls.py
from django.urls import path

from .views import (
    cart_add,
    open_cart,
    clear_cart,
    remove_from_cart,
)

app_name = 'cart'

urlpatterns = [
    path('<int:pk>/', cart_add, name='cart_add'),
    path('open-cart/', open_cart, name='open_cart'),
    path('clear-cart/', clear_cart, name='clear_cart'),
    path('remove-from-cart/<int:pk>/', remove_from_cart, name='remove_from_cart'),
]

e_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from e_shop import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('booklover/', include('bookshop.urls')),
    path('cart/', include('cart.urls')),
    path('payment/', include('liqpay_api.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookshop/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.urls import reverse



class Category(models.Model):
    title = models.CharField('Назва категорії', max_length=50)
    subcategory = models.ManyToManyField('Subcategory', blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('category_detail', args=(self.pk,))


class Subcategory(models.Model):
    title = models.CharField('*Назва підкатегорії', max_length=50)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('subcategory_detail', args=(self.pk,))


class Book(models.Model):
    LANGUAGE = (
        ('українська', 'Українська'),
        ('російська', 'Російська'),
        ('англійська', 'Англійська')
    )

    ILLUSTRATIONS = (
        ('чорно-білі', 'Чорно-білі'),
        ('багатокольорові', 'Багатокольорові'),
        ('без зображень', 'Без зображень')
    )

    PALETTE = (
        ('тверда', 'Тверда'),
        ("м'яка", "М'яка")
    )

    PAPER = (
        ('офсетний', 'Офсетний'),
        ('мелований', 'Мелований'),
    )

    BOOK_TYPE = (
        ('паперова', 'Паперова'),
        ('електронна', 'Електронна')
    )

    author = models.ManyToManyField(
        'Author',
        verbose_name='Автор',
        blank=True,
        default='Не обрано'
    )

    interpreter = models.ManyToManyField(
        'Interpreter',
        verbose_name='Перекладач',
        blank=True,
        default='Не обрано',
    )

    illustrator = models.ManyToManyField(
        'Illustrator',
        verbose_name='Ілюстратор',
        blank=True,
        default='Не обрано',
    )

    publisher = models.ForeignKey(
        'Publisher',
        verbose_name='*Видавництво',
        on_delete=models.SET_DEFAULT,
        default='Не обрано'
    )

    book_series = models.ForeignKey(
        'BookSeries',
        verbose_name='Серія книг',
        on_delete=models.SET_DEFAULT,
        default='Не обрано',
        blank=True
    )

    category = models.ForeignKey(
        'Subcategory',
        verbose_name='Категорія',
        on_delete=models.SET_DEFAULT,
        default='Не обрано',
        blank=True
    )

    edition = models.IntegerField(verbose_name='Тираж', blank=True, null=True)
    weight = models.IntegerField(verbose_name='Вага', blank=True, null=True)
    first_publication_year = models.IntegerField(verbose_name='Рік першого видання', blank=True, null=True)
    rating = models.IntegerField(verbose_name='Рейтинг', default=0, blank=True, null=True)

    price = models.IntegerField(verbose_name='*Ціна')
    publication_year = models.IntegerField(verbose_name='*Рік видання')
    page_count = models.IntegerField(verbose_name='*Кількість сторінок')

    language = models.CharField(choices=LANGUAGE, max_length=15, verbose_name='*Мова')
    palette = models.CharField(choices=PALETTE, max_length=30, verbose_name='*Палітурка')
    paper = models.CharField(choices=PAPER, max_length=30, verbose_name='*Папір')
    book_type = models.CharField(choices=BOOK_TYPE, max_length=30, verbose_name='*Тип')

    Illustrations = models.CharField(choices=ILLUSTRATIONS, max_length=25, verbose_name='Ілюстрації', blank=True,
                                     null=True)

    title = models.CharField('*Назва книги', null=True, max_length=100)
    format = models.CharField('*Формат книги (приклад: 145х215 мм)', max_length=100)
    isbn = models.CharField('*isbn', max_length=25)
    code_product = models.CharField('*Код товару', max_length=9)

    cover_photo = models.ImageField('*Фото', upload_to='img')

    description = models.TextField(null=True, verbose_name='Усе про книжку')

    def __str__(self):
        return f'{self.title}: ({self.code_product})'

    def get_absolute_url(self):
        return reverse('book_detail', args=(self.pk,))

    def average_rating(self):
        review_list = [int(i.rating) for i in Review.objects.filter(book=self)]
        rating = sum(review_list) / len(review_list)
        return int(rating)

    def absolute_average_rating(self):
        review_list = [int(i.rating) for i in Review.objects.filter(book=self)]
        rating = sum(review_list) / len(review_list)
        return round(rating, 1)

    def get_rating_by_grade(self):
        review_list = [int(i.rating) for i in Review.objects.filter(book=self)]
        length = len(review_list)
        star_1, star_2, star_3, star_4, star_5 = [True for star in review_list if star in (1,)], \
                                                 [True for star in review_list if star in (2,)], \
                                                 [True for star in review_list if star in (3,)], \
                                                 [True for star in review_list if star in (4,)], \
                                                 [True for star in review_list if star in (5,)]
        star_1, star_2, star_3, star_4, star_5 = sum(star_1) * 100 // length, \
                                                 sum(star_2) * 100 // length, \
                                                 sum(star_3) * 100 // length, \
                                                 sum(star_4) * 100 // length, \
                                                 sum(star_5) * 100 // length

        return star_1, star_2, star_3, star_4, star_5

    def count_review(self):
        review_list = ['.' for i in Review.objects.filter(book=self)]
        return len(review_list)


class Author(models.Model):
    name = models.CharField("*Ім'я автора", max_length=100)

    birthdate = models.DateField('Дата народження', blank=True, null=True)
    death_date = models.DateField('Дата смерті', blank=True, null=True)
    biography = models.TextField('Біографія', blank=True, null=True)
    photo = models.ImageField('Фото', upload_to='img', blank=True, null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('author_detail', args=(self.pk,))


class Publisher(models.Model):
    title = models.CharField('*Назва видавництва', max_length=100)
    photo = models.ImageField('*Фото', upload_to='img')
    info = models.TextField('*Опис видавництва')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('publisher_detail', args=(self.pk,))


class BookSeries(models.Model):
    title = models.CharField('*Серія книг', max_length=100)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('bookseries_detail', args=(self.pk,))


class Interpreter(models.Model):
    title = models.CharField('*Перекладач', max_length=100)

    def __str__(self):
        return self.title


class Illustrator(models.Model):
    title = models.CharField('*Ілюстратор', max_length=100)

    def __str__(self):
        return self.title


class CustomerOrder(models.Model):
    order_items = models.TextField()
    mail = models.CharField(max_length=100, verbose_name='Електронна пошта')
    city = models.CharField(max_length=100, verbose_name='Місто доставки')
    post_department = models.CharField(max_length=150, verbose_name='Поштове відділення(номер, адреса)')
    phone_number = models.CharField(max_length=15, null=True, verbose_name='Номер телефона')
    status_success = models.BooleanField(null=True)
    total_price = models.IntegerField()
    date = models.DateField(auto_now_add=True, null=True)

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        blank=True,
        null=True
    )

    def __str__(self):
        return f'{self.date}'

    def get_absolute_url(self):
        return reverse('order_detail', args=(self.pk,))


class Review(models.Model):
    RATING = (
        ('1', 'Жахливо'),
        ('2', 'Погано'),
        ('3', 'Середньо'),
        ('4', 'Добре'),
        ('5', 'Чудово')
    )

    title = models.CharField('Заголовок', max_length=100)
    body = models.TextField('Рецензія', max_length=2500)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    rating = models.CharField('Рейтинг', choices=RATING, max_length=100)


    def __str__(self):
        return f'{self.user}: {self.title}'

    def count_like(self):
        like_list = LikeReview.objects.filter(review=self)
        return len(like_list)

    def count_dislike(self):
        like_list = DislikeReview.objects.filter(review=self)
        return len(like_list)


class LikeDislikeManager(models.Manager):

    def get_or_none(self, **kwargs):
        try:
            return self.get(**kwargs)
        except ObjectDoesNotExist:
            return None


class LikeReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)

    objects = LikeDislikeManager()


class DislikeReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)

    objects = LikeDislikeManager()

bookshop/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.models import User

from bookshop.models import CustomerOrder, Review


class CustomerOrderForm(forms.ModelForm):
    class Meta:
        model = CustomerOrder
        fields = ['mail', 'city', 'post_department', 'phone_number']


class RegistrationUserForm(forms.ModelForm):
    username = forms.CharField(required=True, max_length=25, label='Логін')
    password = forms.CharField(max_length=30, required=True, widget=forms.PasswordInput(), label='пароль')
    password_confirm = forms.CharField(max_length=30, required=True, widget=forms.PasswordInput(), label='пароль')
    email = forms.EmailField(required=True, label='електронна пошта')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('зареєструватися', 'Зареєструватися'))

    class Meta:
        model = User
        fields = ('username', 'email', 'password', 'password_confirm')

    def clean_password_confirm(self):
        password_one = self.cleaned_data.get('password')
        password_two = self.cleaned_data.get('password_confirm')
        password_has_num = [True for sym in password_one if sym.isdigit()]

        if password_one != password_two:
            raise forms.ValidationError('Паролі не співпадають')
        if len(password_one) < 8:
            raise forms.ValidationError('Пароль має бути довше 8 символів')
        if not password_one[0].isalpha():
            raise forms.ValidationError('Перший символ у паролі має бути великою літерою')
        if not password_one[0].isupper():
            raise forms.ValidationError('Перший символ у паролі має бути великою літерою')
        if not sum(password_has_num) > 0:
            raise forms.ValidationError('Пароль повинен містити хоча б одне число')

        return password_two

    def clean_email(self):
        email = self.cleaned_data.get('email')
        check_mail = User.objects.filter(email=email)

        if len(check_mail) > 0:
            raise forms.ValidationError('Ця електронна адреса вже використовується')

        return email


class LoginUserForm(forms.Form):
    username = forms.CharField(required=True, max_length=25, label='Логін')
    password = forms.CharField(max_length=30, required=True, widget=forms.PasswordInput(), label='Пароль')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('увійти', 'Увійти'))

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        check_username = User.objects.filter(username=username)

        if not len(check_username):
            raise forms.ValidationError('Користувача с таким логіном не знайдено')

        check_password = authenticate(username=username, password=password)

        if check_password is None:
            raise forms.ValidationError('Неправильний пароль')

        return self.cleaned_data


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['title', 'body', 'rating']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('залишити рецензiю', 'Залишити рецензiю'))

bookshop/templates/bookshop/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'bookshop/css/main.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Книголюб</title>
</head>
<body>

<header>
    <nav style="background: #F0EBD8" class="navbar navbar-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home_page' %}">
                <strong style="color: #0D1321">
                    Книголюб
                </strong>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="#">
                            <text-nav class="text-nav">
                                Домашня сторінка
                            </text-nav>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="#">
                            <text-nav class="text-nav">
                                Про книголюба
                            </text-nav>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="#">
                            <text-nav class="text-nav">
                                Акції
                            </text-nav>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="#">
                            <text-nav class="text-nav">
                                Оплата
                            </text-nav>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="#">
                            <text-nav class="text-nav">
                                Контакти
                            </text-nav>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="#">
                            <text-nav class="text-nav">
                                Блог
                            </text-nav>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <nav style="background: #F0EBD8" class="navbar navbar-light">
        <div class="container">
            <div class="row">
                <div class="col-12"></div>
                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Пошук" aria-label="Search">
                    <button class="btn btn-outline-dark" type="submit">Знайти</button>
                </form>
            </div>
        </div>
    </nav>

    <nav style="background: #F0EBD8" class="navbar navbar-light">
        <div class="container">
            <div class="accordion" id="accordionExample">
                <div class="accordion-item">
                    <h2 class="accordion-header" id="headingOne">
                        <button class="accordion-button" type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne"
                                style="background: #748CAB; color: #F0EBD8">
                            Каталог товарів
                        </button>
                    </h2>
                    <div id="collapseOne" class="accordion-collapse collapse show"
                         aria-labelledby="headingOne"
                         data-bs-parent="#accordionExample">
                        <div class="accordion-body">
                            <div class="list-group">
                                {% for category in category_list %}
                                    <a href="{{ category.get_absolute_url }}"
                                       class="list-group-item list-group-item-action">
                                        {{ category }}
                                    </a>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>

    <nav style="background: #F0EBD8" class="navbar navbar-light">
        <div class="container">
            <div class="row gy-2">
                <div class="col">
                    <a style="text-decoration: none" href="{% url 'cart:open_cart' %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor"
                             class="bi bi-cart" viewBox="0 0 16 16">
                            <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                        </svg>
                        Корзина
                    </a>
                </div>
                <div class="col">
                    <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor"
                         class="bi bi-person-circle" viewBox="0 0 16 16">
                        <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                        <path fill-rule="evenodd"
                              d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                    </svg>
                    {% if user_is_active %}
                        Вітаємо, <a style="text-decoration: none" href="{% url 'personal_account' %}">
                        {{ user.username }}
                    </a>
                    {% else %}
                        <a style="text-decoration: none" href="{% url 'login_view' %}">
                            Особистий кабінет
                        </a>
                    {% endif %}
                </div>
                {% if user_is_active %}
                    <div class="col">
                        <a href="{% url 'logout' %}">вийти</a>
                    </div>
                {% endif %}
            </div>
        </div>
    </nav>

</header>

{% block content %} {% endblock %}

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>

</body>
</html>